### ISSUE TITLE
/usr/bin/python: No module named SimpleHTTPServer

### ISSUE THREAD

**Issue by hbons** [garrett/magicmockup#1]
[hbons@myhost magicmockup]$ ./webserver.sh 
Visit http://localhost:8000/demo.svg
/usr/bin/python: No module named SimpleHTTPServer

which deps do i need? :(

**Comment by oswaldojr** [comment]
Working! Thanks garaPM

**Comment by cryptox31** [comment]
If it still does not work write the following code and it should work

`import SimpleHTTPServer 
import SocketServer
PORT = 8000
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
httpd = SocketServer.TCPServer(("", PORT), Handler)
print "serving at port", PORT
httpd.serve_forever()`

**Comment by donbright** [comment]
yeah this is some mid 2010s stuff, doesnt work in these modern, tough times.

**Comment by niranjanreddy891** [comment]
Use `python -m http.server`. It works for me. :)

**Comment by aruntirath** [comment]
I think you are using python3. For python3 instead of `python -m SimpleHTTPServer` you should use 
`python3 -m http.server`

**Comment by malkhazx** [comment]
@aruntirath thx man, it's work.

**Comment by garrett** [comment]
I've updated the script for Python 3.

https://github.com/garrett/magicmockup/commit/be4e913b066980cc3b07cfa0a302f9728b2d46ab

We last worked on this repo around 9 years ago. I guess it's still working (aside from the Python version issue)?

**Comment by garrett** [comment]
I've updated the CoffeeScript to work with CoffeeScript 2 and recompiled the JS. Additionally, I've (slightly) modified the README to drop the Ruby reference and go with just NPM for installing CoffeeScript.

It's a start.

It's at https://github.com/garrett/magicmockup/pull/17 — I might get the chance to update things coming soon, but if anyone else could test out the branch and provide feedback, that would be appreciated. Perhaps we can modernize things. :wink:

**Comment by savetheword** [comment]
> Try with python3 -m http.server 8000.

Thanks!

**Comment by Bnke0x0** [comment]
use python3 -m http.server  80  or python -m http.serve 8080

**Comment by HackerInfo2024** [comment]
@garaPM surprised to find this 9 years later and worked. Exactly what I was looking for.Thanks
